---
name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@d388a4836fcdbde0e50e395dc79a2670ccdef13f  # stable
        with:
          toolchain: '1.76.0'
          target: x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  cargo-fmt:
    name: Ensure 'cargo fmt' has been run
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@d388a4836fcdbde0e50e395dc79a2670ccdef13f  # stable
        with:
          components: rustfmt
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4
      - run: cargo fmt -- --check

  cargo-audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4
      - run: cargo audit
