---
name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@d388a4836fcdbde0e50e395dc79a2670ccdef13f  # stable
        with:
          toolchain: '1.86.0'
          target: x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
